name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-20.04
    container:
      image: node:12.22
    services:
      postgres:
        image: postgres:9.4
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Install dependencies
        env:
          POSTGRES_HOST: postgres
          POSTGRES_PORT: 5432
          PGPASSWORD: postgres
        run: |
          apt update
          apt install -qy postgresql-client libgtk-3-0 libdbus-glib-1-2 sudo
          wget -O FirefoxSetup.tar.bz2 "https://download.mozilla.org/?product=firefox-latest&os=linux64&lang=en-US"
          mkdir /opt/firefox
          tar xjf FirefoxSetup.tar.bz2 -C /opt/firefox/
          ln -s /opt/firefox/firefox/firefox /usr/bin/firefox
          psql -h postgres -p 5432 -c 'create database zappr;' -U postgres
          psql -h postgres -p 5432 -c 'create schema zappr_data; create schema zappr_meta;' -U postgres zappr
          npm install
          npm install pg
      - name: Run unit tests
        env:
          DISPLAY: ":99:0"
          DB_HOST: postgres
          DB_PASSWORD: "postgres"
          KARMA_BROWSER: FirefoxHeadless
        run: |
          npm test
          sudo -E npm run test-karma
